import {Course} from './course';
import { CourseType } from './course-type';

export const COURSES: Course[] = [
    {   id: 1,
        name: 'WDAI',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        rating: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 2,
        name: 'Fizyka',
        ECTS: 6,
        term: 3,
        type: CourseType.Classes,
        capacity: 30,
        rating: 4,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 3,
        name: 'Programowanie obiektowe',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        rating: 5,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 4,
        name: 'Logika',
        ECTS: 3,
        term: 2,
        type: CourseType.Lecture,
        capacity: 200,
        rating: 3,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 5,
        name: 'Algebra',
        ECTS: 6,
        term: 1,
        type: CourseType.Classes,
        capacity: 30,
        rating: 4,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 6,
        name: 'Systemy operacyjne',
        ECTS: 6,
        term: 4,
        type: CourseType.Lecture,
        capacity: 200,
        rating: 2,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 7,
        name: 'Równania różniczkowe i różnicowe',
        ECTS: 4,
        term: 3,
        type: CourseType.Lecture,
        capacity: 200,
        rating: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 8,
        name: 'Algorytmy i struktury danych',
        ECTS: 6,
        term: 2,
        type: CourseType.Lecture,
        capacity: 200,
        rating: 4,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 9,
        name: 'Matematyka dyskretna',
        ECTS: 4,
        term: 1,
        type: CourseType.Classes,
        capacity: 30,
        rating: 3,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    },
    {   id: 10,
        name: 'Inżynieria wymagań i jakości',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        rating: 4,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg'
    }
];
