import {Course} from './course';
import { CourseType } from './course-type';

export const COURSES: Course[] = [
    {   id: 1,
        rating: undefined,
        name: 'Wprowadzenie do aplikacji internetowych',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        ratingSum: 4,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 2,
        rating: undefined,
        name: 'Fizyka',
        ECTS: 6,
        term: 3,
        type: CourseType.Classes,
        capacity: 30,
        ratingSum: 4,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 3,
        rating: undefined,
        name: 'Programowanie obiektowe',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        ratingSum: 5,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 4,
        rating: undefined,
        name: 'Logika',
        ECTS: 3,
        term: 2,
        type: CourseType.Lecture,
        capacity: 200,
        ratingSum: 3,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 5,
        rating: undefined,
        name: 'Algebra',
        ECTS: 6,
        term: 1,
        type: CourseType.Classes,
        capacity: 30,
        ratingSum: 4,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 6,
        rating: undefined,
        name: 'Systemy operacyjne',
        ECTS: 6,
        term: 4,
        type: CourseType.Lecture,
        capacity: 200,
        ratingSum: 2,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 7,
        rating: undefined,
        name: 'Równania różniczkowe i różnicowe',
        ECTS: 4,
        term: 3,
        type: CourseType.Lecture,
        capacity: 200,
        ratingSum: 1,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 8,
        rating: undefined,
        name: 'Algorytmy i struktury danych',
        ECTS: 6,
        term: 2,
        type: CourseType.Lecture,
        capacity: 200,
        ratingSum: 4,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 9,
        rating: undefined,
        name: 'Matematyka dyskretna',
        ECTS: 4,
        term: 1,
        type: CourseType.Classes,
        capacity: 30,
        ratingSum: 3,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    },
    {   id: 10,
        rating: undefined,
        name: 'Inżynieria wymagań i jakości',
        ECTS: 3,
        term: 3,
        type: CourseType.Lab,
        capacity: 15,
        ratingSum: 4,
        ratingNo: 1,
        pictureUrl: 'https://i.ytimg.com/vi/BAy94LXkQOI/maxresdefault.jpg',
        hide: true
    }
];
